1]
#NON EQUI JOIN
SELECT U.UNAME,U.AGE,L.ALLOW_AGE
FROM USER_1 U
JOIN LOGIN L
ON(U.U_ID=L.U_ID)
WHERE U.AGE<L.ALLOW_AGE

2]
#INNER JOIN
1]
SELECT U.U_ID,U.UNAME,P.POST_ID,P.POST_CONTENT
FROM USER_1 U
INNER JOIN POST P
ON U.U_ID=P.U_ID
SELECT * FROM USER_1
SELECT * FROM POST

2]
#NATURAL JOIN
SELECT * FROM POST
NATURAL JOIN USER_1

3]
#ON CLAUSE JOIN
SELECT U.U_ID,U.UNAME,M.MSG_TEXT,DELIVEREDAT
FROM USER_1 U JOIN MESSAGE M 
ON (U.U_ID = M.U_ID)
WHERE M.DELIVEREDAT IS NULL

4]
#USING CLAUSE JOIN
SELECT * FROM USER_1
JOIN POST
USING(U_ID)

5]
#SELF JOIN
SELECT U.UNAME AS USERNAME,M.UNAME AS MUSERNAME
FROM USER_1 U JOIN USER_1 M
ON(U.U_ID=M.U_ID)
-----------------------------------------------------------------------------------------------------------------
3]
#OUTER JOIN
1]
#LEFT JOIN
SELECT G.GROUP_ID,G.G_NAME,GM.GM_ID,GM.ROLE
FROM GROUP1 G LEFT JOIN GROUP_MEMBER GM
ON(G.GROUP_ID=GM.GROUP_ID)
ORDER BY GROUP_ID ASC

2]
#RIGHT JOIN
SELECT G.GROUP_ID,G.G_NAME,GM.GM_ID,GM.ROLE
FROM GROUP1 G RIGHT JOIN GROUP_MEMBER GM
ON(G.GROUP_ID=GM.GROUP_ID)
ORDER BY GROUP_ID ASC

3]
#FULL OUTER
SELECT P.POST_ID,P.POST_CONTENT,C.COMMENT_ID,C.COMMENT_TEXT
FROM POST P
FULL OUTER JOIN POST_COMMENTS C
ON(P.POST_ID=C.POST_ID)
---------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------