1]
#NON EQUI JOIN
SELECT U.UNAME,U.AGE,L.ALLOW_AGE
FROM USER_1 U
JOIN LOGIN L
ON(U.U_ID=L.U_ID)
WHERE U.AGE<L.ALLOW_AGE

2]
#INNER JOIN
1]
SELECT U.U_ID,U.UNAME,P.POST_ID,P.POST_CONTENT
FROM USER_1 U
INNER JOIN POST P
ON U.U_ID=P.U_ID
SELECT * FROM USER_1
SELECT * FROM POST

2]
#NATURAL JOIN
SELECT * FROM POST
NATURAL JOIN USER_1

3]
#ON CLAUSE JOIN
SELECT U.U_ID,U.UNAME,M.MSG_TEXT,DELIVEREDAT
FROM USER_1 U JOIN MESSAGE M 
ON (U.U_ID = M.U_ID)
WHERE M.DELIVEREDAT IS NULL

4]
#USING CLAUSE JOIN
SELECT * FROM USER_1
JOIN POST
USING(U_ID)

5]
#SELF JOIN
SELECT U.UNAME AS USERNAME,M.UNAME AS MUSERNAME
FROM USER_1 U JOIN USER_1 M
ON(U.U_ID=M.U_ID)
-----------------------------------------------------------------------------------------------------------------
3]
#OUTER JOIN
1]
#LEFT JOIN
SELECT G.GROUP_ID,G.G_NAME,GM.GM_ID,GM.ROLE
FROM GROUP1 G LEFT JOIN GROUP_MEMBER GM
ON(G.GROUP_ID=GM.GROUP_ID)
ORDER BY GROUP_ID ASC

2]
#RIGHT JOIN
SELECT G.GROUP_ID,G.G_NAME,GM.GM_ID,GM.ROLE
FROM GROUP1 G RIGHT JOIN GROUP_MEMBER GM
ON(G.GROUP_ID=GM.GROUP_ID)
ORDER BY GROUP_ID ASC

3]
#FULL OUTER
SELECT P.POST_ID,P.POST_CONTENT,C.COMMENT_ID,C.COMMENT_TEXT
FROM POST P
FULL OUTER JOIN POST_COMMENTS C
ON(P.POST_ID=C.POST_ID)

#join using all tables info
SELECT U.*,L.*,PR.*,P.*,PL.*,PC.*,PT.*,PH.*,L1.*,GM.*,G.*,F.*,MF.*,M.*,NM.*,N.*
FROM USER_1 U JOIN LOGIN L
ON(U.U_ID=L.U_ID)
JOIN PRIVACY1 PR
ON(L.LID=PR.LID)
JOIN POST P
ON(P.U_ID=U.U_ID)
JOIN POST_LIKES PL
ON(P.POST_ID=PL.POST_ID)
JOIN POST_COMMENTS PC
ON(P.POST_ID=PC.POST_ID)
JOIN POST_TAG PT
ON(P.POST_ID=PT.POST_ID)
JOIN PHOTOS PH
ON(P.POST_ID=PH.POST_ID)
JOIN LOCATION L1
ON(L1.LOCATION_ID=PH.LOCATION_ID)
JOIN GROUP_MEMBER GM
ON(U.U_ID=GM.U_ID)
JOIN GROUP1 G
ON(G.GROUP_ID=GM.GROUP_ID)
JOIN FRIENDS F
ON(F.GROUP_ID=G.GROUP_ID)
JOIN MESS_FRI MF
ON(MF.FRIENDS_ID=F.FRIENDS_ID)
JOIN MESSAGE M
ON(M.M_ID=MF.M_ID)
JOIN NOTI_MESS NM
ON(NM.M_ID=M.M_ID)
JOIN NOTIFICATION N
ON(N.N_ID=NM.N_ID)
WHERE LID='&X1'

---------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------
