
1]
CREATE TABLE USER_1(U_ID NUMBER(10)CONSTRAINT U_ID_PK PRIMARY KEY,UNAME VARCHAR2(20),EMAIL VARCHAR2(30),
PASS_WORD VARCHAR2(30),PROFILE_PHOTO VARCHAR2(40),DOB DATE,GENDER VARCHAR2(10),AGE NUMBER(10))

2]
CREATE TABLE LOGIN(LID NUMBER(20),U_ID NUMBER UNIQUE,LOGIN_DATE_TIME TIMESTAMP,LOGIN_DEVICE VARCHAR2(30),
LOCATION_ID NUMBER(20),CITY VARCHAR2(20),IP_ADDRESS VARCHAR2(30),
CONSTRAINT LID_PK PRIMARY KEY(LID),CONSTRAINT U_ID_FK FOREIGN KEY(U_ID) REFERENCES USER_1(U_ID))

3]
CREATE TABLE PRIVACY1(PI_D NUMBER(10),LID NUMBER(20),ACCOUNT_TYPE VARCHAR2(20),PROFILE_VISIBILITY VARCHAR2(20),
LAST_SEEN VARCHAR2(20),STORY_VISIBLITY VARCHAR2(20),
BLOCK_ACCOUNT VARCHAR2(20),MESSAGE_PRIVACY VARCHAR2(20),MENTION_PRIVACY VARCHAR2(20),TAGGING_PRIVACY VARCHAR2(20),
CONSTRAINT PI_D_PK PRIMARY KEY(PI_D),CONSTRAINT LID_FK FOREIGN KEY(LID) REFERENCES LOGIN(LID))

4]
CREATE TABLE POST(POST_ID NUMBER(20),U_ID NUMBER(10),POST_CONTENT VARCHAR2(20),PRIVACY VARCHAR2(20),
POST_DATE DATE,POST_IMAGE VARCHAR2(255),POST_VIDEO VARCHAR2(255),STATUS VARCHAR2(20),
CONSTRAINT POST_ID PRIMARY KEY(POST_ID),CONSTRAINT U_ID FOREIGN KEY(U_ID)REFERENCES USER_1(U_ID))

5]
CREATE TABLE POST_LIKES(LIKE_ID NUMBER(20),POST_ID NUMBER(20),LIKE_DATE DATE,LIKE_DEVICE_ID NUMBER(20),VERIFIED_USER VARCHAR2(20),
IP_ADDRESS1 VARCHAR2(20),
CONSTRAINT LIKE_ID_PK PRIMARY KEY(LIKE_ID),CONSTRAINT POST_ID_FK FOREIGN KEY(POST_ID)REFERENCES POST(POST_ID))

6]
CREATE TABLE POST_COMMENTS(COMMENT_ID NUMBER(30),POST_ID NUMBER(20),COMMENT_ICON VARCHAR2(255),
COMMENT_TEXT VARCHAR2(20),DELETED_AT TIMESTAMP,IS_PINNED VARCHAR2(20),
CONSTRAINT COMMENT_ID_HD PRIMARY KEY(COMMENT_ID),CONSTRAINT POST_ID_DH FOREIGN KEY(POST_ID)REFERENCES POST(POST_ID))

7]
CREATE TABLE POST_TAG(POST_TAG_ID NUMBER(20),POST_ID NUMBER(20),TAG_NAME VARCHAR2(20),TAG_BY NUMBER(10),TAG_VISIBILITY VARCHAR2(20),
CONSTRAINT PK_POST_TAG_ID PRIMARY KEY(POST_TAG_ID),CONSTRAINT FK_POST_ID FOREIGN KEY(POST_ID)REFERENCES POST(POST_ID))

8]
CREATE TABLE PHOTOS(PHOTO_ID NUMBER(20),POST_ID NUMBER(20),
LOCATION_ID NUMBER(20),CAPTION VARCHAR2(20),UPLOAD_DATE DATE,IMAGE_URL VARCHAR2(500),PHOTO_FORMAT VARCHAR2(20),
CONSTRAINT ST_PHOTO_ID PRIMARY KEY(PHOTO_ID),CONSTRAINT ST_POST_ID FOREIGN KEY(POST_ID)REFERENCES POST(POST_ID),
CONSTRAINT ST_LOCATION_ID FOREIGN KEY(LOCATION_ID)REFERENCES LOCATION(LOCATION_ID))

9]
CREATE TABLE LOCATION(LOCATION_ID NUMBER(20)CONSTRAINT LOCATION_ID_PK PRIMARY KEY,LOCATION_NAME VARCHAR2(20),LOCATION_TYPE VARCHAR(20),
COUNTRY VARCHAR2(20),CITY VARCHAR2(20),LATITUDE DECIMAL(10,8),LONGITUDE DECIMAL(11,8),VISIT_COUNT NUMBER(30))

10]
CREATE TABLE GROUP1(GROUP_ID NUMBER(20)CONSTRAINT GROUP_ID_PK PRIMARY KEY,G_NAME VARCHAR2(20),CREATE_DATE DATE,
CREATOR_ID NUMBER(20),DESCRIPTION VARCHAR2(50))

11]
CREATE TABLE GROUP_MEMBER(GM_ID NUMBER(20),ROLE VARCHAR2(30),JOIN_DATE DATE,GROUP_ID NUMBER,U_ID NUMBER(20),STATUS VARCHAR2(20),
LAST_ACTIVE TIMESTAMP,INVITEBY NUMBER(20),
CONSTRAINT GM_ID_PK PRIMARY KEY(GM_ID),CONSTRAINT GROUP_ID_FK FOREIGN KEY(GROUP_ID)REFERENCES GROUP1(GROUP_ID),
CONSTRAINT FK_U_ID FOREIGN KEY(U_ID)REFERENCES USER_1(U_ID))

12]
CREATE TABLE FRIENDS(FRIENDS_ID NUMBER(20),GROUP_ID NUMBER(20),U_ID NUMBER(20),STATUS VARCHAR2(30),REQUESTSENTAT TIMESTAMP,ACCEPTEDAT TIMESTAMP,
BLOCKKAT TIMESTAMP,REMOVEAT TIMESTAMP,
CONSTRAINT FRIENDS_ID_PK PRIMARY KEY(FRIENDS_ID),CONSTRAINT FK_GROUP_ID_ FOREIGN KEY(GROUP_ID)REFERENCES GROUP1(GROUP_ID),
CONSTRAINT HD_U_ID FOREIGN KEY(U_ID)REFERENCES USER_1(U_ID))

13]
CREATE TABLE MESSAGE(M_ID NUMBER(20)CONSTRAINT M_ID_PK PRIMARY KEY,MSG_TEXT VARCHAR2(30),SENDER_ID NUMBER(30),RECEIVER_ID NUMBER(30),SENDAT TIMESTAMP,DELIVEREDAT TIMESTAMP,
READAT TIMESTAMP,ISFORWARDED VARCHAR2(20),REACTIONTYPE VARCHAR2(30),DELETEDAT TIMESTAMP)

14]
CREATE TABLE MESS_FRI(FRIENDS_ID NUMBER(20),M_ID NUMBER(20),
CONSTRAINT FRIENDS_ID_FK FOREIGN KEY(FRIENDS_ID)REFERENCES FRIENDS(FRIENDS_ID),
CONSTRAINT M_ID_FK FOREIGN KEY(M_ID)REFERENCES MESSAGE(M_ID))

15]
CREATE TABLE NOTIFICATION(N_ID NUMBER(20)CONSTRAINT N_ID_PK PRIMARY KEY,SENDER_ID NUMBER(20),SEEN_STATUS VARCHAR2(20),
ISREAD VARCHAR2(20),READAT TIMESTAMP,ISDELIVERED VARCHAR2(20),DELIVEREDAT TIMESTAMP,
ISPINNED VARCHAR2(20),ISARCHIVED VARCHAR2(20),ISMUTED VARCHAR2(20),N_DATE DATE)

16]
CREATE TABLE NOTI_MESS(N_ID NUMBER(20),M_ID NUMBER(20),
CONSTRAINT N_ID_FK FOREIGN KEY(N_ID)REFERENCES NOTIFICATION(N_ID),
CONSTRAINT FK_M_ID FOREIGN KEY(M_ID)REFERENCES MESSAGE(M_ID))

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------